AllCops:
  Exclude:
    - vendor/**/*

Metrics/LineLength:
  Max: 200

Style/FileName:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets
  Exclude:
    - spec/**/*
    - Rakefile

Style/SpaceBeforeFirstArg:
  Enabled: false

Metrics/BlockLength:
  Max: 75
