AllCops:
  Exclude:
    - vendor/**/*

Metrics/LineLength:
  Max: 200

Style/FileName:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets
  Exclude:
    - spec/**/*
    - Rakefile

Layout/SpaceBeforeFirstArg:
  Enabled: false
  
Lint/ScriptPermission:
  Exclude:
    - Rakefile

Metrics/BlockLength:
  Max: 75
