name             'magento-ng'
maintainer       'Andy Thompson'
maintainer_email 'athompson@inviqa.com'
license          'All rights reserved'
description      'Installs/Configures magento-ng'
long_description 'Installs/Configures magento-ng'
version          '0.3.1'

depends 'config-driven-helper', '~> 1.5'
depends 'cron', '~> 1.4'
depends 'logrotate', '~> 1.9'
depends 'php-fpm'
